language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - laravel=^7.0
    - laravel=^6.0
    - laravel=5.8.x
    - laravel=5.7.x
    - laravel=5.6.x

matrix:
  include:
    - php: 7.0
      env: laravel=5.5.x
  exclude:
    - php: 7.1
      env: laravel=^6.0
    - php: 7.1
      env: laravel=^7.0

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - phpenv config-rm xdebug.ini

install:
  - if [ $laravel != 'default' ]; then travis_retry composer require illuminate/support:${laravel} --no-update --no-interaction; fi
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit --verbose
